import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import StyledComponentsRegistry from "../lib/registry";
import "../styles/globals.css";

import Loading from "@/components/loading";
import dynamic from "next/dynamic";
import { Suspense } from "react";

const Navbar = dynamic(() => import("@/components/navbar"), { ssr: false });
const Container = dynamic(() => import("@/components/layout"), { ssr: false });

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={openSans.className}>
        <StyledComponentsRegistry>
          <Container>
            <Navbar />
            <div className="content">
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </div>
          </Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
